In [4]:
import tensorflow as tf
import numpy as np
tf.set_random_seed(777)

xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

# print(x_data.shape, x_data, len(x_data))
# print(y_data.shape, y_data, len(y_data))

X = tf.placeholder(tf.float32, shape=[None,3])
Y = tf.placeholder(tf.float32, shape=[None,1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b
cost = tf.reduce_mean(tf.square(hypothesis-Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# learn
sess = tf.Session()
sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X:x_data, Y:y_data})
    if step%100 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val, "\n")

0 Cost:  35677.168 
Prediction:
 [[-20.254536]
 [-31.873005]
 [-27.520107]
 [-31.092148]
 [-25.062668]
 [-20.705004]] 

100 Cost:  11.224851 
Prediction:
 [[156.85732]
 [181.32086]
 [182.37675]
 [197.50996]
 [137.6054 ]
 [ 99.27431]] 

200 Cost:  10.613948 
Prediction:
 [[156.71121]
 [181.394  ]
 [182.31908]
 [197.46556]
 [137.70786]
 [ 99.40739]] 

300 Cost:  10.041877 
Prediction:
 [[156.56985]
 [181.46472]
 [182.2633 ]
 [197.42244]
 [137.80713]
 [ 99.53595]] 

400 Cost:  9.506167 
Prediction:
 [[156.43317]
 [181.53317]
 [182.20941]
 [197.38058]
 [137.90335]
 [ 99.66019]] 

500 Cost:  9.004435 
Prediction:
 [[156.30093]
 [181.59943]
 [182.15729]
 [197.33997]
 [137.99658]
 [ 99.7802 ]] 

600 Cost:  8.5345955 
Prediction:
 [[156.17307]
 [181.66354]
 [182.10696]
 [197.30057]
 [138.08696]
 [ 99.89614]] 

700 Cost:  8.09447 
Prediction:
 [[156.04936]
 [181.7256 ]
 [182.05829]
 [197.26228]
 [138.17455]
 [100.00814]] 

800 Cost:  7.682239 
Prediction:
 [[155.92975]
 [181.78568]
 [182.01126]

In [9]:
print("Your score will be ", sess.run(hypothesis, feed_dict={X:[[100, 70, 101]]}))
print("Other scores will be ", sess.run(hypothesis, feed_dict={X:[[60, 70, 110], [90, 100, 80]]}))

Your score will be  [[173.12749]]
Other scores will be  [[165.6122 ]
 [183.53804]]


In [5]:
import tensorflow as tf
filename_queue = tf.train.string_input_producer(['data-02-test-score.csv'], shuffle=False, name='filename_queue')

reader = tf.TextLineReader()
key, val = reader.read(filename_queue)

record_defaults = [[0.], [0.], [0.], [0.]]
xy = tf.decode_csv(val, record_defaults=record_defaults)

train_x_batch, train_y_batch = tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)

X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])
W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X:x_batch, Y:y_batch})
    if step%100 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val, "\n")

coord.request_stop()
coord.join(threads)
        

0 Cost:  388035.9 
Prediction:
 [[-410.13568]
 [-489.04776]
 [-483.70126]
 [-530.4128 ]
 [-368.74442]
 [-276.45923]
 [-410.13568]
 [-489.04776]
 [-483.70126]
 [-530.4128 ]] 

100 Cost:  4.2583494 
Prediction:
 [[145.58089]
 [102.66968]
 [150.88058]
 [185.27623]
 [180.70712]
 [193.13582]
 [145.58089]
 [102.66968]
 [150.88058]
 [185.27623]] 

200 Cost:  4.8056235 
Prediction:
 [[180.55287]
 [192.96408]
 [145.39073]
 [102.51025]
 [150.79506]
 [185.05997]
 [180.55287]
 [192.96408]
 [145.39073]
 [102.51025]] 

300 Cost:  3.489251 
Prediction:
 [[150.83908]
 [185.00323]
 [180.55376]
 [192.96169]
 [145.32289]
 [102.44202]
 [150.83908]
 [185.00323]
 [180.55376]
 [192.96169]] 

400 Cost:  3.823716 
Prediction:
 [[145.4259 ]
 [102.5007 ]
 [151.0654 ]
 [185.16957]
 [180.77242]
 [193.19675]
 [145.4259 ]
 [102.5007 ]
 [151.0654 ]
 [185.16957]] 

500 Cost:  4.4169626 
Prediction:
 [[180.62555]
 [193.03404]
 [145.2477 ]
 [102.35286]
 [150.98189]
 [184.9665 ]
 [180.62555]
 [193.03404]
 [145.2477 ]
 [1