In [5]:
import tensorflow as tf

x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]
y_data = [152., 185., 180., 196., 142.]

x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')
hypothesis = x1*w1 + x2*w2 + x3*w3 + b

cost = tf.reduce_mean(tf.square(hypothesis-Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={x1:x1_data, x2:x2_data, x3:x3_data, Y:y_data})
    
    if step%10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)


0 Cost:  26274.879 
Prediction:
 [ 2.7723088 15.544823   9.56839    6.7672963 17.362587 ]
10 Cost:  21.527954 
Prediction:
 [146.12262 187.80994 179.32037 191.62187 148.7506 ]
20 Cost:  21.185404 
Prediction:
 [146.57278 188.31981 179.83891 192.18544 149.13263]
30 Cost:  21.083675 
Prediction:
 [146.59053 188.31003 179.84538 192.1914  149.11832]
40 Cost:  20.98251 
Prediction:
 [146.60692 188.2987  179.85033 192.1957  149.10286]
50 Cost:  20.881882 
Prediction:
 [146.62329 188.28745 179.85526 192.2     149.08746]
60 Cost:  20.781717 
Prediction:
 [146.6396  188.2762  179.86017 192.2043  149.07208]
70 Cost:  20.682144 
Prediction:
 [146.65587 188.26495 179.86504 192.20854 149.05675]
80 Cost:  20.583014 
Prediction:
 [146.67209 188.25375 179.8699  192.2128  149.04143]
90 Cost:  20.484573 
Prediction:
 [146.68825 188.24261 179.87479 192.21706 149.02618]
100 Cost:  20.386566 
Prediction:
 [146.70439 188.23148 179.87962 192.22125 149.01096]
110 Cost:  20.289083 
Prediction:
 [146.72047 188.

In [7]:
import tensorflow as tf

x_data = [[73., 80., 75.], [93., 88., 93.], [89., 91., 90.], [96., 98., 100.], [73., 66., 70.]]
y_data = [[152.], [185.], [180.], [196.], [142.]]

X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X:x_data, Y:y_data})
    if step%10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  18303.453 
Prediction:
 [[31.316433]
 [40.316864]
 [38.22501 ]
 [42.5905  ]
 [30.712467]]
10 Cost:  1.0108238 
Prediction:
 [[150.99251]
 [184.1608 ]
 [179.95576]
 [196.9315 ]
 [140.42992]]
20 Cost:  0.8423773 
Prediction:
 [[151.35347]
 [184.59683]
 [180.3843 ]
 [197.3979 ]
 [140.76326]]
30 Cost:  0.8414742 
Prediction:
 [[151.35342]
 [184.59897]
 [180.38528]
 [197.39871]
 [140.76564]]
40 Cost:  0.84059954 
Prediction:
 [[151.3523 ]
 [184.5998 ]
 [180.38501]
 [197.39816]
 [140.76703]]
50 Cost:  0.839708 
Prediction:
 [[151.35115]
 [184.6006 ]
 [180.38469]
 [197.39757]
 [140.7684 ]]
60 Cost:  0.8388295 
Prediction:
 [[151.35004]
 [184.60143]
 [180.3844 ]
 [197.397  ]
 [140.76978]]
70 Cost:  0.8379483 
Prediction:
 [[151.3489 ]
 [184.60223]
 [180.3841 ]
 [197.39642]
 [140.77115]]
80 Cost:  0.83708256 
Prediction:
 [[151.34776]
 [184.60304]
 [180.3838 ]
 [197.39584]
 [140.7725 ]]
90 Cost:  0.83620834 
Prediction:
 [[151.34665]
 [184.60384]
 [180.38348]
 [197.39526]
 [140.77386]]