In [7]:
import tensorflow as tf
import numpy as np
tf.set_random_seed(777)

xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

# print(x_data.shape, x_data, len(x_data))
# print(y_data.shape, y_data, len(y_data))

X = tf.placeholder(tf.float32, shape=[None,3])
Y = tf.placeholder(tf.float32, shape=[None,1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b
cost = tf.reduce_mean(tf.square(hypothesis-Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# learn
sess = tf.Session()
sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X:x_data, Y:y_data})
    if step%100 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  7912.228 
Prediction:
 [[74.180595]
 [80.63322 ]
 [83.980225]
 [91.3227  ]
 [59.210712]
 [41.890907]]
100 Cost:  17.500559 
Prediction:
 [[157.38617]
 [180.99034]
 [182.68105]
 [198.83252]
 [135.82275]
 [ 98.44156]]
200 Cost:  16.540762 
Prediction:
 [[157.20383]
 [181.08197]
 [182.60938]
 [198.77563]
 [135.95256]
 [ 98.60641]]
300 Cost:  15.641562 
Prediction:
 [[157.02744]
 [181.17065]
 [182.5401 ]
 [198.72037]
 [136.07838]
 [ 98.76565]]
400 Cost:  14.799221 
Prediction:
 [[156.85687]
 [181.25652]
 [182.47318]
 [198.66675]
 [136.20038]
 [ 98.91945]]
500 Cost:  14.009967 
Prediction:
 [[156.69186]
 [181.33958]
 [182.40848]
 [198.61462]
 [136.31863]
 [ 99.068  ]]
600 Cost:  13.270473 
Prediction:
 [[156.53233]
 [181.42003]
 [182.346  ]
 [198.56404]
 [136.43333]
 [ 99.21147]]
700 Cost:  12.577514 
Prediction:
 [[156.37802]
 [181.49788]
 [182.28561]
 [198.5149 ]
 [136.54454]
 [ 99.35003]]
800 Cost:  11.92806 
Prediction:
 [[156.22876]
 [181.57323]
 [182.22723]
 [198.46713]
 [136

In [9]:
print("Your score will be ", sess.run(hypothesis, feed_dict={X:[[100, 70, 101]]}))
print("Other scores will be ", sess.run(hypothesis, feed_dict={X:[[60, 70, 110], [90, 100, 80]]}))

Your score will be  [[173.12749]]
Other scores will be  [[165.6122 ]
 [183.53804]]


In [3]:
import tensorflow as tf
filename_queue = tf.train.string_input_producer(['data-02-test-score.csv'], shuffle=False, name='filename_queue')

reader = tf.TextLineReader()
key, val = reader.read(filename_queue)

record_defaults = [[0.], [0.], [0.], [0.]]
xy = tf.decode_csv(val, record_defaults=record_defaults)

train_x_batch, train_y_batch = tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)

X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])
W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X:x_batch, Y:y_batch})
    if step%100 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

coord.request_stop()
coord.join(threads)
        

0 Cost:  212341.88 
Prediction:
 [[-270.26025]
 [-309.3765 ]
 [-312.80624]
 [-342.6648 ]
 [-230.0779 ]
 [-170.14122]
 [-270.26025]
 [-309.3765 ]
 [-312.80624]
 [-342.6648 ]]
100 Cost:  43.170555 
Prediction:
 [[149.70145]
 [109.69581]
 [144.41812]
 [188.6376 ]
 [178.10281]
 [191.89958]
 [149.70145]
 [109.69581]
 [144.41812]
 [188.6376 ]]
200 Cost:  35.460957 
Prediction:
 [[177.73122]
 [191.452  ]
 [149.13039]
 [109.15109]
 [144.29478]
 [188.00172]
 [177.73122]
 [191.452  ]
 [149.13039]
 [109.15109]]
300 Cost:  28.907032 
Prediction:
 [[144.47726 ]
 [187.7504  ]
 [177.72963 ]
 [191.40904 ]
 [148.85548 ]
 [108.829254]
 [144.47726 ]
 [187.7504  ]
 [177.72963 ]
 [191.40904 ]]
400 Cost:  35.60888 
Prediction:
 [[149.11302]
 [108.90421]
 [145.22433]
 [188.19365]
 [178.40405]
 [192.1038 ]
 [149.11302]
 [108.90421]
 [145.22433]
 [188.19365]]
500 Cost:  29.56023 
Prediction:
 [[178.06154]
 [191.6924 ]
 [148.59108]
 [108.40818]
 [145.10747]
 [187.61194]
 [178.06154]
 [191.6924 ]
 [148.59108]
 [