In [4]:
import tensorflow as tf

x_data = [[1, 2], [2, 3], [3, 1], [4, 3], [5, 3], [6, 2]]
y_data = [[0], [0], [0], [1], [1], [1]]

X = tf.placeholder(tf.float32, shape=[None, 2])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([2, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.sigmoid(tf.matmul(X, W) + b)
cost = -tf.reduce_mean(Y*tf.log(hypothesis) + (1-Y)*tf.log(1-hypothesis))
train = tf.train.GradientDescentOptimizer(learning_rate=0.01).minimize(cost)

predicted = tf.cast(hypothesis>0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

# Launch Graph
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(10001):
        cost_val, _ = sess.run([cost, train], feed_dict={X:x_data, Y:y_data})
        if step%1000 == 0:
            print(step, cost_val)
    
    h, c, a = sess.run([hypothesis, predicted, accuracy], feed_dict={X:x_data, Y:y_data})
    print("\nHypothesis:\n", h, "\nCorrect (Y):\n", c, "\nAccuracy:\n", a)

0 0.4554427
1000 0.35760233
2000 0.30685428
3000 0.26782003
4000 0.23694211
5000 0.21209985
6000 0.19179977
7000 0.17496689
8000 0.16081952
9000 0.14878298
10000 0.13842918

Hypothesis:
 [[0.02622562]
 [0.15223405]
 [0.28248364]
 [0.79180354]
 [0.945953  ]
 [0.9823307 ]] 
Correct (Y):
 [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 
Accuracy:
 1.0


In [14]:
import numpy as np

xy = np.loadtxt('data-03-diabetes.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]
print(y_data)

X = tf.placeholder(tf.float32, shape=[None, 8])
Y = tf.placeholder(tf.float32, shape=[None, 1])
W = tf.Variable(tf.random_normal([8,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.sigmoid(tf.matmul(X, W) + b)
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1-Y)*tf.log(hypothesis))
train = tf.train.GradientDescentOptimizer(learning_rate=0.01).minimize(cost)

predicted = tf.cast(hypothesis>0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    feed = {X:x_data, Y:y_data}
    for step in range(10001):
        sess.run(train, feed_dict=feed)
        if step%500==0:
            print(step, sess.run(cost, feed_dict=feed))
    
    h, c, a = sess.run([hypothesis, predicted, accuracy], feed_dict=feed)
    print("\nHypothesis:\n", h, "\nCorrect (Y) :\n", c, "Accuracy:\n", a)

[[1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]]
0 0.20949426
500 0.090420194
1000 0.057862803
1500 0.042610295
2000 0.033738285
2500 0.027928574
3000 0.02382674
3500 0.020775432
4000 0.018416636
4500 0.016538499
5000 0.015007767
5500 0.0137361325
6000 0.012663007
6500 0.011745314
7000 0.010951497
7500 0.010258091
8000 0.009647274
8500 0.0091050705
9000 0.008620497
9500 0.008184911
10000 0.007791207

Hypothesis:
 [[0.9961127 ]
 [0.99542755]
 [0.99602485]
 [0.9982236 ]
 [0.9955422 ]
 [0.99754554]
 [0.99660397]
 [0.9629404 ]] 
Correct (Y) :
 [[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]] Accuracy:
 0.5
