In [9]:
import tensorflow as tf

x_data = [[1, 2, 1, 1], [2, 1, 3, 1], [3, 1, 3, 4], [4, 1, 5, 5], [1, 7, 5, 5], [1, 2, 5, 6], [1, 6, 6, 6], [1, 7, 7, 7]]
y_data = [[0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 1, 0], [0, 1, 0], [0, 1, 0], [1, 0, 0], [1, 0, 0]]

X = tf.placeholder("float", [None, 4])
Y = tf.placeholder("float", [None, 3])
nb_classes = 3

W = tf.Variable(tf.random_normal([4, nb_classes]), name='weight')
b = tf.Variable(tf.random_normal([nb_classes]), name='bias')

hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)
cost = tf.reduce_mean(-tf.reduce_sum(Y*tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(2001):
        sess.run(optimizer, feed_dict={X: x_data, Y: y_data})
        if step%200 == 0:
            print(step, sess.run(cost, feed_dict={X: x_data, Y: y_data}))
            
    a = sess.run(hypothesis, feed_dict={X:[[1, 11, 7, 9]]})
    print(a, sess.run(tf.arg_max(a, 1)))
    
    all = sess.run(hypothesis, feed_dict={X:[[1, 11, 7, 9], [1, 3, 4, 3], [1, 1, 0, 1]]})
    print(all, sess.run(tf.arg_max(all, 1)))

0 3.7715514
200 0.5270249
400 0.43733543
600 0.3652659
800 0.2959125
1000 0.23228484
1200 0.20949125
1400 0.19118991
1600 0.17574745
1800 0.16255099
2000 0.1511513
[[1.7580152e-02 9.8240477e-01 1.5051088e-05]] [1]
[[1.7580142e-02 9.8240477e-01 1.5051071e-05]
 [7.5733346e-01 2.3786148e-01 4.8050331e-03]
 [1.7011544e-08 4.8416510e-04 9.9951577e-01]] [1 0 2]
